source 'https://rubygems.org'

gem 'appium_capybara'
gem 'capybara'
gem 'cucumber'
gem 'cuke_modeler', '~> 3.0'
gem 'parallel_tests'
gem 'pry'
gem 'require_all', '= 1.5.0'
gem 'testcentricity_web', '~> 4.1.7'
